services:
  - type: web
    name: iran-news-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run iran_news_app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHONUNBUFFERED
        value: true