services:
  - type: web
    name: iran-news-aggregator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run translate_app.py --server.port 10000 --server.address 0.0.0.0
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
